name: Run tests
on:
  workflow_call:

permissions:
  contents: read

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - run: npm run all
